import { Link } from "wouter";

const playtestImage = "/manus-storage/ironveil-playtest-crossing_1e3bff1b.png";
const lanternMark = "/manus-storage/ironveil-lantern-mark_d1d947ac.png";

const downloads = [
 ["01", "The Playtest Package", "Start here: current version, scope, audience, and how to report what happened at your table.", "https://github.com/ironveilpress/threl-public-playtest/blob/main/playtest/overview/Threl_Playtest_CANON_CORRECTED.md"],
 ["02", "Player Quick Reference", "Phrase cards, six-box Strain, Failure Echoes, Conditions, Force It, and recovery in one page.", "https://github.com/ironveilpress/threl-public-playtest/blob/main/playtest/player/Threl_MVP_Player_Quick_Reference.md"],
 ["03", "Ashenfold Scenario", "The corrected Prodigal Dungeon module: a wounded estate, a family that left something behind, and a place that asks what restoration costs.", "https://github.com/ironveilpress/threl-public-playtest/blob/main/playtest/module/The_Prodigal_Dungeon_CANON_CORRECTED.pdf"],
 ["04", "Phrase Cards", "Prepared, printed-cost cards for the module’s ordinary MVP play.", "https://github.com/ironveilpress/threl-public-playtest/blob/main/playtest/module/The_Prodigal_Dungeon_Module_Phrase_Cards.md"],
 ["05", "GM Reference", "Failure Echoes, Strain recovery, Conditions, Force It, and the boundary between ordinary play and advanced systems.", "https://github.com/ironveilpress/threl-public-playtest/blob/main/playtest/gm/Threl_GM_Failure_Echoes_Strain_Reference.md"],
 ["06", "Pregenerated Characters", "Six-box Strain, class resources kept separate, and characters ready to bring to the table.", "https://github.com/ironveilpress/threl-public-playtest/blob/main/playtest/player/The_Prodigal_Dungeon_Pregenerated_Characters_CANON_CORRECTED.pdf"],
];

export default function Playtest() {
 return <div className="site-shell playtest-page">
 <header className="site-header playtest-header"><a className="brand" href="/"><img src={lanternMark} alt="" className="brand-mark" /><span><b>IRON VEIL</b><em>PRESS</em></span></a><nav aria-label="Playtest navigation"><Link href="/">Home</Link><a href="#downloads">Downloads</a><a href="#boundaries">Rules boundary</a><a href="#feedback">Feedback</a></nav><a className="header-cta" href="https://github.com/ironveilpress/threl-public-playtest">View repository <span>↗</span></a></header>
 <main>
 <section className="playtest-hero" style={{ backgroundImage: `url(${playtestImage})` }}><div className="hero-shade" /><div className="wrap playtest-hero-content"><p className="eyebrow"><span className="lantern-dot" /> Public playtest · v0.1 MVP</p><h1>Enter<br /><i>Ashenfold.</i></h1><p>Test the Minimum Viable Dabar system in a dark-fantasy scenario about inheritance, repair, and the cost of pretending a wound has closed.</p><div className="hero-actions"><a className="button button-gold" href="#downloads">Choose your materials <span>↓</span></a><a className="text-link" href="https://github.com/ironveilpress/threl-public-playtest/blob/main/CHANGELOG.md">Read the changelog <span>↗</span></a></div></div></section>
 <section className="playtest-intro section"><div className="wrap split-heading"><div><p className="eyebrow">A living world, open to the table</p><h2>Run it.<br /><i>Leave marks.</i></h2></div><div className="intro-copy"><p>The Threl is shaped by the players and Game Masters who enter it. This release is designed for one short campaign or a focused convention session. It gives you a complete path from table setup to feedback without requiring private lore or unreleased material.</p><div className="stat-row"><div><b>1</b><span>scenario</span></div><div><b>6</b><span>prepared characters</span></div><div><b>8</b><span>module Phrase cards</span></div></div><div className="field-note-strip"><span><b>STATUS</b> Current public build</span><span><b>SCOPE</b> MVP Dabar + Ashenfold</span><span><b>REPORT</b> Tell us what the table became</span></div></div></div></section>
 <section className="downloads section" id="downloads"><div className="wrap"><div className="section-head"><div><p className="eyebrow">Download the current set</p><h2>Take only<br /><i>what you need.</i></h2></div><p className="section-note">All links open from the public repository. The set is versioned so your feedback can name exactly what you played.</p></div><div className="field-note-label"><span className="lantern-dot" /> Expedition packet · current release</div><div className="download-list">{downloads.map(([n,title,desc,href]) => <a className="download-row" href={href} key={n}><span className="download-no">{n}</span><div><h3>{title}</h3><p>{desc}</p></div><span className="download-arrow">↗</span></a>)}</div></div></section>
 <section className="boundaries section" id="boundaries"><div className="wrap boundary-grid"><div><p className="eyebrow">Know the boundary</p><h2>What is<br /><i>experimental?</i></h2></div><div className="boundary-copy"><p><b>Ordinary MVP play</b> uses prepared Phrase cards with printed DCs and Strain costs, one roll, Failure Echoes, named Conditions, Force It at 6 Strain, and Short/Long Rest recovery.</p><p><b>Not ordinary MVP authority:</b> World Drift scores, glyph arithmetic, Backlash tables, and stacked environmental modifiers. Those may appear in design notes or an explicitly labeled advanced trial, but they are not required to run this release.</p><p><b>Public boundary:</b> this package does not include secret Warden lore, private Frey Wars history, internal audits, or unreleased canon decisions.</p></div></div></section>
 <section className="feedback section" id="feedback"><div className="wrap feedback-box"><div><p className="eyebrow">After the session</p><h2>Tell us what<br /><i>the table became.</i></h2></div><div><p>We want reports that help us see the rules in motion: where a Phrase felt clear, where Strain created useful pressure, where a Failure Echo surprised the table, and where the fiction asked for a better tool.</p><a className="button button-outline" href="https://github.com/ironveilpress/threl-public-playtest/issues/new/choose">Submit playtest feedback <span>↗</span></a><p className="fine-print">Please do not include private player information. Session summaries, rules observations, and respectful critique are welcome.</p></div></div></section>
 </main>
 <footer className="site-footer"><div className="wrap footer-bottom"><span>© 2026 Iron Veil Press</span><span>The current public playtest is a work in motion.</span><Link href="/">Return to Iron Veil Press ↑</Link></div></footer>
 </div>;
}
